CREATE TABLE IF NOT EXISTS review_cases (
    review_case_id VARCHAR(32) PRIMARY KEY,
    image_filename VARCHAR(255) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reviewers (
    reviewer_id VARCHAR(100) PRIMARY KEY,
    reviewer_role VARCHAR(20) NOT NULL
        CHECK (reviewer_role IN ('primary', 'adjudicator', 'admin')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reviewer_assignments (
    reviewer_id VARCHAR(100) NOT NULL REFERENCES reviewers(reviewer_id),
    review_case_id VARCHAR(32) NOT NULL REFERENCES review_cases(review_case_id),
    assignment_type VARCHAR(20) NOT NULL
        CHECK (assignment_type IN ('full', 'adjudication', 'calibration')),
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    assigned_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (reviewer_id, review_case_id),
    UNIQUE (reviewer_id, display_order)
);

CREATE TABLE IF NOT EXISTS expert_reviews (
    reviewer_id VARCHAR(100) NOT NULL REFERENCES reviewers(reviewer_id),
    review_case_id VARCHAR(32) NOT NULL REFERENCES review_cases(review_case_id),
    expert_label VARCHAR(10) NOT NULL
        CHECK (expert_label IN ('PASS', 'WARN', 'FAIL')),
    reason_sealed_decline BOOLEAN NOT NULL DEFAULT FALSE,
    reason_spike BOOLEAN NOT NULL DEFAULT FALSE,
    reason_transition_issue BOOLEAN NOT NULL DEFAULT FALSE,
    reason_vent_response BOOLEAN NOT NULL DEFAULT FALSE,
    reason_data_quality BOOLEAN NOT NULL DEFAULT FALSE,
    reason_other BOOLEAN NOT NULL DEFAULT FALSE,
    confidence INTEGER NOT NULL CHECK (confidence BETWEEN 1 AND 5),
    comment TEXT NOT NULL DEFAULT '',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    app_version VARCHAR(30) NOT NULL,
    PRIMARY KEY (reviewer_id, review_case_id)
);

CREATE TABLE IF NOT EXISTS assignment_audit_log (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_id VARCHAR(100) NOT NULL,
    review_case_id VARCHAR(32) NOT NULL,
    action VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_assignments_active_reviewer
    ON reviewer_assignments (reviewer_id, is_active, display_order);
CREATE INDEX IF NOT EXISTS ix_reviews_case
    ON expert_reviews (review_case_id);
CREATE INDEX IF NOT EXISTS ix_audit_created
    ON assignment_audit_log (created_at);

-- The app uses a direct PostgreSQL connection. No anon/authenticated Data API
-- policies are created, so Supabase API clients cannot read these tables.
ALTER TABLE review_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviewers ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviewer_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expert_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignment_audit_log ENABLE ROW LEVEL SECURITY;
